@url = http://localhost:3034

### simple users READ
GET {{url}}/simpleUsers
content-type: application/json

### simple users CREATE
POST {{url}}/simpleUsers/create
content-type: application/json
 
{
    "firstName": "Andre",
    "lastName": "Hackerkrug"
}

### simple users UPDATE
PATCH {{url}}/simpleUsers/update/619d83eed2fb430e6e4c376a
content-type: application/json
 
{
    "lastName": "Lastname-Changed"
}