@url = http://localhost:3034

### simple users READ
GET {{url}}/simpleUsers
content-type: application/json

### simple users CREATE
POST {{url}}/simpleUsers/create
content-type: application/json
 
{
    "firstName": "Andre",
    "lastName": "Hackerkrug"
}

### simple users UPDATE
PATCH {{url}}/simpleUsers/update/619e10090862c1bc1af16b75
content-type: application/json
 
{
    "lastName": "Lastname-Changed55555",
    "firstName": "Elis"
}

### simple users DELETE
DELETE {{url}}/simpleUsers/delete/619e10090862c1bc1af16b75
content-type: application/json

### nested users READ
GET {{url}}/nestedUsers
content-type: application/json